#%RAML 1.0
title: financialservices-aisp
version: v1
baseUri: https://localhost:8081/api/{version}
protocols: HTTP

securitySchemes:
  oauth_2_0:
    description: |
      {title} supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid OAuth 2 access token. Do not use
             with the "access_token" query string parameter.
          type: string
   
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token. Do not use with
             the "Authorization" header.
          type: string
          
    settings:
        authorizationUri: https://financial-services-auth.cloudhub.io/api/v1/oauth2/authorize
        accessTokenUri: https://financial-services-auth.cloudhub.io/api/v1/oauth2/token
        authorizationGrants: [ authorization_code, implicit ]

/account/{acrtoken}:
  uriParameters:
    acrtoken:
      type: string
      description : acr token
  /info:
    displayName: info about the account
    get:
      description: get info about the account
      responses:
        200: 
          body:
            application/json: 
              example: !include account-info-response.json
  /transactions:
    displayName: info about the transactions of the account
    get:
      description: get info about the transactions
      responses:
        200: 
          body:
            application/json:
              example: !include account-transactions-response.json
  /balance:
    displayName: info about the balance
    get:
      description: get info about the balance of the account
      responses:
        200: 
          body:
            application/json:
              example:  !include account-balance-response.json
